#! /bin/bash
#
#$Author$
#$Date$
#$HeadURL$
#$Revision$

[[ $# != 1 ]] && echo "usage: .bash <filename>" && exit 1

[[ ! -r $1 ]] && echo "$1 is not readable" && exit 2

exec 3< $1
read line <&3
read line <&3

echo $line | cut -d " " -f6
