#! /bin/bash
#
#$Author: ee364c07 $
#$Date: 2016-01-12 16:52:04 -0500 (Tue, 12 Jan 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364c07/Lab00/Script2 $
#$Revision: 84233 $

for ((i=$1; i >= 0; i--))
do
    echo $i
done
