#! /bin/bash
#
#$Author: ee364c07 $
#$Date: 2016-01-12 16:56:22 -0500 (Tue, 12 Jan 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364c07/Lab00/Script3 $
#$Revision: 84240 $

for ((i=$1; i >= 0; i--))
do
    if (($i % 3 == 0))
    then
        echo $i
    fi
done
